# Generated by Django 2.1.2 on 2018-12-29 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('red', models.IntegerField(default=0)),
                ('green', models.IntegerField(default=0)),
                ('blue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hold_time', models.IntegerField()),
                ('fade_time', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ledstate',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='led.Profile'),
        ),
        migrations.AddField(
            model_name='currentledstate',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='led.Profile'),
        ),
    ]
