# Generated by Django 2.1.1 on 2019-01-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0002_auto_20181229_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentledstate',
            name='blue',
        ),
        migrations.RemoveField(
            model_name='currentledstate',
            name='green',
        ),
        migrations.RemoveField(
            model_name='currentledstate',
            name='red',
        ),
    ]
